# Generated by Django 4.1.2 on 2023-02-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('Name', models.CharField(max_length=20)),
                ('Email', models.CharField(max_length=40)),
                ('Phonenumber', models.CharField(blank=True, max_length=12)),
                ('StudentID', models.CharField(max_length=10)),
                ('Introduction', models.TextField()),
                ('Favorite', models.TextField()),
            ],
            options={
                'db_table': 'Userfile',
            },
        ),
    ]
