# Generated by Django 4.1.2 on 2023-03-05 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfile',
            name='Profliephoto',
            field=models.CharField(default='', max_length=50, verbose_name='address'),
        ),
    ]
