# Generated by Django 4.1.2 on 2023-03-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userfile_profliephoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='Profliephoto',
            field=models.CharField(default='', max_length=50),
        ),
    ]
