# Generated by Django 4.1.2 on 2023-04-19 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userfile_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chathistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sender', models.CharField(max_length=20)),
                ('Receiver', models.CharField(max_length=20)),
                ('Type', models.CharField(max_length=10)),
                ('Content', models.CharField(max_length=255)),
                ('Date', models.CharField(max_length=2)),
                ('Time', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'ChatHistory',
            },
        ),
    ]
