# Generated by Django 4.1.2 on 2023-07-02 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.CharField(default='', max_length=20, verbose_name='用戶名稱')),
                ('Commodity_ID', models.CharField(max_length=10, verbose_name='購物車商品ID')),
            ],
            options={
                'db_table': 'Cart',
            },
        ),
    ]
