# Generated by Django 4.1.2 on 2023-07-02 02:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Commodity',
            new_name='Cart',
        ),
    ]
