# Generated by Django 4.1.2 on 2023-07-06 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_commodity_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='Seller',
            field=models.CharField(default='', max_length=20, verbose_name='賣家名稱'),
        ),
    ]
