# Generated by Django 4.1.2 on 2023-03-24 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Commodity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Launched', models.BooleanField(default=False, verbose_name='商品上架狀態')),
                ('Img1', models.CharField(max_length=25)),
                ('Img2', models.CharField(blank=True, max_length=25)),
                ('Img3', models.CharField(blank=True, max_length=25)),
                ('Img4', models.CharField(blank=True, max_length=25)),
                ('Img5', models.CharField(blank=True, max_length=25)),
                ('Name', models.CharField(max_length=20)),
                ('Deacription', models.TextField()),
                ('Price', models.CharField(max_length=5)),
                ('Amount', models.CharField(max_length=5)),
                ('Position', models.TextField()),
            ],
        ),
    ]
