# Generated by Django 4.1.2 on 2023-03-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='Account',
            field=models.CharField(default='', max_length=20),
        ),
    ]
