# Generated by Django 4.1.2 on 2023-06-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0002_commodity_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commodity',
            name='Account',
            field=models.CharField(default='', max_length=20, verbose_name='賣場名稱'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='Amount',
            field=models.CharField(max_length=5, verbose_name='商品數量'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='Deacription',
            field=models.TextField(verbose_name='商品描述'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='Img1',
            field=models.CharField(max_length=45, verbose_name='圖片名稱(必須)'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='Img2',
            field=models.CharField(blank=True, max_length=45, verbose_name='圖片名稱(可選)'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='Img3',
            field=models.CharField(blank=True, max_length=45, verbose_name='圖片名稱(可選)'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='Img4',
            field=models.CharField(blank=True, max_length=45, verbose_name='圖片名稱(可選)'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='Img5',
            field=models.CharField(blank=True, max_length=45, verbose_name='圖片名稱(可選)'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='Name',
            field=models.CharField(max_length=45, verbose_name='商品名稱'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='Position',
            field=models.TextField(verbose_name='商品位置'),
        ),
        migrations.AlterField(
            model_name='commodity',
            name='Price',
            field=models.CharField(max_length=5, verbose_name='商品價格'),
        ),
    ]
