# Generated by Django 4.1.2 on 2023-07-09 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commodity', '0003_alter_commodity_account_alter_commodity_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commodity',
            name='BorrowedAmount',
            field=models.CharField(default='0', max_length=5, verbose_name='已借出的數量'),
        ),
    ]
