# Generated by Django 4.1.2 on 2023-07-16 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Order_ID', models.CharField(max_length=255, verbose_name='訂單UUID')),
                ('Consumer', models.CharField(max_length=255, verbose_name='買家名稱')),
                ('Provider', models.CharField(max_length=255, verbose_name='賣家名稱')),
                ('Order', models.JSONField(verbose_name='訂單資訊')),
                ('Totalprice', models.CharField(max_length=255, verbose_name='訂單總價格')),
                ('Comment', models.CharField(max_length=255, verbose_name='買家留言')),
                ('Options', models.JSONField(verbose_name='買家提供的地點,時間')),
                ('Selected_Option', models.JSONField(verbose_name='賣家選擇的地點,時間')),
                ('Using_Message', models.BooleanField(verbose_name='是否使用訊息討論交貨地點')),
                ('Actual', models.JSONField(verbose_name='實際租借時間')),
                ('Progress', models.CharField(max_length=10, verbose_name='訂單進度')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
