# Generated by Django 4.1.2 on 2023-07-31 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Comment',
            field=models.CharField(blank=True, max_length=255, verbose_name='買家留言'),
        ),
    ]
