# Generated by Django 4.1.2 on 2023-07-31 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_order_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='Progress',
            field=models.IntegerField(verbose_name='訂單進度'),
        ),
    ]
